[project]
name = "lab-algo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "momode12", email = "heritianajulien12@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.11.1",
    "numpy>=2.4.6",
    "pandas>=3.0.5",
    "scikit-learn>=1.9.0",
    "scipy>=1.17.1",
    "xgboost>=3.2.0",
]

[project.scripts]
lab-algo = "lab_algo:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
